# Favicon
favicon: /favicon.ico

# SEO
keywords: "Java Python R 机器学习 统计 扯淡"

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  blog: /archives
  github: https://github.com/pingao777

# Nav menu
menu:
  Home: /archives
  About: /about
  RSS: /atom.xml
